variable "ami" {}
variable "instance_type" {}
variable "count" {}
variable "key_name" {}
variable "Created_by" {}
variable "Env" {}
variable "Dept" {}
variable "min_size" {}
variable "max_size" {}
variable "Appname" {}
variable "desired_capacity" {}
variable "DBname" {}
variable "db_min_size" {}
variable "db_max_size" {}
variable "db_desired_capacity" {}
variable "db_ami" {}
variable "db_instance_type" {}